---
# tasks file for lighthouse-role
- name: Lighthouse | Install Dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Create Lighthouse directory
  become: true
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'
    selevel: s0
    serole: object_r
    setype: httpd_sys_content_t
    seuser: unconfined_u      
- name: Lighthouse | Clone from Git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
    force: yes
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify: restart-nginx